name = "MarkovCats"
uuid = "1c3ceaae-476a-497b-bab1-fd4a0242b34a"
version = "0.1.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphsMatching = "c3af3a8c-b79e-4b01-bf44-c718d7e0e0d6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Catlab = "0.17.3"
GraphViz = "0.2.0"
HiGHS = "1.20.1"
MathOptInterface = "1.46.0"
Test = "1.11.0"
